import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="min-h-screen bg-[linear-gradient(to_bottom,rgba(30,58,138,0.95),rgba(255,255,255,0.03))]">
            <Header />
            <main className="mx-auto max-w-5xl px-4 py-10">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
